'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Name_Modifier.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blitz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blitz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonPA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonPA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonPB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonPB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonPX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonPX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonZl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonZl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonZr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonZr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property codemgr() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("codemgr", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property wii1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wii1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wii2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wii2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wiiA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wiiA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wiiB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wiiB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wiIC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wiIC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wiiDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wiiDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wiiLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wiiLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wiiMinus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wiiMinus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wiimote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wiimote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wiiNun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wiiNun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wiiPlus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wiiPlus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wiiPlus1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wiiPlus1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wiiRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wiiRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wiiUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wiiUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wiiZ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wiiZ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
